---
version: 1
author: Oli
language: Python
image: python
code: /
workdir: /
cmd: python3 src/%zeroday%/main.py
persistence: []
daypath: "src/day%zeroday%/main.py"
inputfile: "src/day%zeroday%/input.txt"
answerfile: "src/day%zeroday%/output.txt"
