---
version: 1
author: Oli
language: Python
image: python:3.12
code: /code
workdir: /code
cmd: python3 src/day%zeroday%/main.py
persistence: []
daypath: "src/day%zeroday%/main.py"
inputfile: "src/day%zeroday%/input.txt"
answerfile: "src/day%zeroday%/output.txt"
